name: realm_dart
description: The official Realm SDK for Dart. Realm is a mobile database - an alternative to SQLite and key-value stores.
version: 0.2.0-alpha

homepage: https://www.realm.io
repository: https://github.com/realm/realm-dart
issue_tracker: https://github.com/realm/realm-dart/issues

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  build_cli_annotations: ^2.0.0
  crypto: ^3.0.0
  ffi: ^1.1.2
  json_annotation: ^4.1.0
  logging: ^1.0.0
  meta: ^1.1.8
  package_config: ^2.0.0
  path: ^1.0.0
  pubspec_parse: ^1.0.0
  realm_generator: 
    path: ./generator

dev_dependencies:
  build_cli: ^2.1.3
  build_runner: ^2.1.2
  build_version: ^2.1.0
  json_serializable: ^5.0.2
  lints: ^1.0.1
  test: ^1.14.3
