name: realm_dart
description: The official Realm SDK for Dart. Realm is a mobile database - an alternative to SQLite and key-value stores.
version: 0.3.1+beta

homepage: https://www.realm.io
repository: https://github.com/realm/realm-dart
issue_tracker: https://github.com/realm/realm-dart/issues

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.0
  build_cli_annotations: ^2.0.0
  crypto: ^3.0.0
  ffi: ^2.0.1
  json_annotation: ^4.4.0
  logging: ^1.0.0
  meta: ^1.1.8
  package_config: ^2.0.0
  path: ^1.0.0
  pubspec_parse: ^1.0.0
  pub_semver: ^2.1.0
  realm_common:
    path: ./common
  realm_generator:
    path: ./generator
  tar: ^0.5.4
  build_runner: ^2.1.0
  http: ^0.13.4

dev_dependencies:
  build_cli: ^2.1.3
  json_serializable: ^6.1.0
  lints: ^2.0.0
  test: ^1.14.3

platforms:
  windows:
  linux:
  macos:

