name: ejson_generator
description: >-
  EJSON serialization.

  BSON is a binary format used to store JSON-like documents efficiently. 
  EJSON extends JSON defining how all BSON types should be represented in JSON.

topics:
  - ejson
  - bson
  - json
  - build-runner
  - codegen

version: 0.4.1
repository: https://github.com/realm/realm-dart/ejson/packages/ejson_generator

environment:
  sdk: ^3.3.0

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.0
  ejson_analyzer: ^0.4.1
  source_gen: ^1.3.2

dev_dependencies:
  build_runner: ^2.4.4
  build_test: ^2.1.7
  dart_style: ^2.3.1
  ejson: ^0.4.1
  ejson_annotation: ^0.4.1
  lints: ^3.0.0
  meta: ^1.9.1
  test: ^1.21.0
