name: realm_dart
description: The official Realm SDK for Dart. Realm is a mobile database - an alternative to SQLite and key-value stores.
version: 20.1.1

homepage: https://www.realm.io
repository: https://github.com/realm/realm-dart
issue_tracker: https://github.com/realm/realm-dart/issues

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.6.0
  build_cli_annotations: ^2.1.0
  collection: ^1.19.0
  crypto: ^3.0.0
  ejson: ^0.4.1
  ffi: ^2.0.1
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ^1.15.0
  package_config: ^2.1.0
  path: ^1.9.0
  pubspec_parse: ^1.0.0
  pub_semver: ^2.1.4
  realm_common: ^20.1.1
  realm_generator: ^20.1.1
  tar: ^2.0.0
  build_runner: ^2.4.14
  http: ^1.2.1
  cancellation_token: ^2.0.0
  decimal: ^3.0.1
  rational: ^2.2.3
  type_plus: ^2.1.1

dev_dependencies:
  build_cli: ^2.2.4
  ffigen: ^18.0.0
  json_serializable: ^6.9.2
  lints: ^5.1.1
  test: ^1.25.9
  timezone: ^0.10.0
  universal_platform: ^1.1.0
