name: realm_dart
description: The official Realm SDK for Dart. Realm is a mobile database - an alternative to SQLite and key-value stores.
version: 1.9.0

homepage: https://www.realm.io
repository: https://github.com/realm/realm-dart
issue_tracker: https://github.com/realm/realm-dart/issues

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.3.0
  build_cli_annotations: ^2.0.0
  collection: ^1.16.0
  crypto: ^3.0.0
  ejson_annotation: ^0.1.0
  ejson: ^0.1.0
  ffi: ^2.0.1
  json_annotation: ^4.7.0
  logging: ^1.2.0
  meta: ^1.1.8
  package_config: ^2.0.0
  path: ^1.0.0
  pubspec_parse: ^1.0.0
  pub_semver: ^2.1.0
  realm_common:
    path: ../realm_common
  realm_generator:
    path: ../realm_generator
  tar: ^1.0.1
  build_runner: ^2.1.0
  http: ^1.0.0
  cancellation_token: ^2.0.0

dev_dependencies:
  build_cli: ^2.2.2
  ejson_generator: ^0.1.0
  json_serializable: ^6.3.1
  lints: ^3.0.0
  test: ^1.14.3
  timezone: ^0.9.0

