name: realm_common
description: >-
             Hosts the common code shared between realm, realm_dart and realm_generator packages.
             This package is part of the official Realm Flutter and Realm Dart SDKs.

version: 0.2.1+alpha

homepage: https://www.realm.io
repository: https://github.com/realm/realm-dart
issue_tracker: https://github.com/realm/realm-dart/issues

dependencies:
  objectid: ^2.0.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1