name: realm_common
description: >-
             Hosts the common code shared between realm, realm_dart and realm_generator packages.
             This package is part of the official Realm Flutter and Realm Dart SDKs.

version: 0.3.0+alpha

homepage: https://www.realm.io
repository: https://github.com/realm/realm-dart
issue_tracker: https://github.com/realm/realm-dart/issues

publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  objectid: ^2.1.0
  sane_uuid: ^1.0.0-alpha.4

dev_dependencies:
  lints: ^1.0.1
