name: realm_generator
description: >-
  Generates RealmObject classes from Realm data model classes.
  This package is part of the official Realm Flutter and Realm Dart SDKs.

version: 20.1.1

homepage: https://www.realm.io
repository: https://github.com/realm/realm-dart
issue_tracker: https://github.com/realm/realm-dart/issues

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: ^7.3.0
  build_resolvers: ^2.4.3
  build: ^2.4.2
  dart_style: ^3.0.1
  realm_common: ^20.1.1
  source_gen: ^2.0.0
  source_span: ^1.8.0
  collection: ^1.19.0

dev_dependencies:
  build_runner: ^2.4.14
  build_test: ^2.2.2
  lints: ^5.1.1
  logging: ^1.2.0
  meta: ^1.15.0
  path: ^1.9.0
  term_glyph: ^1.2.0
  test: ^1.25.9
  pub_semver: ^2.2.0
