name: realm_generator
description: >-
             Generates RealmObject classes from Realm data model classes.
             This package is part of the official Realm Flutter and Realm Dart SDKs.

version: 2.2.1

homepage: https://www.realm.io
repository: https://github.com/realm/realm-dart
issue_tracker: https://github.com/realm/realm-dart/issues

environment:
  sdk: ^3.3.0

dependencies:
  analyzer: ^6.0.0
  build_resolvers: ^2.0.9
  build: ^2.0.0
  dart_style: ^2.2.0
  realm_common: ^2.2.1
  source_gen: ^1.1.0
  source_span: ^1.8.0
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.1.0
  build_test: ^2.1.4
  lints: ^3.0.0
  logging: ^1.2.0
  meta: ^1.7.0
  path: ^1.0.0
  term_glyph: ^1.2.0
  test: ^1.14.3
