name: realm_example
description: Demonstrates how to use the Realm SDK for Flutter.
version: 1.9.0

publish_to: "none"

environment:
  sdk: ^3.0.0
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  realm: ^1.8.0
  characters: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
