name: realm_example
description: Demonstrates how to use the Realm SDK for Flutter.
version: 2.0.0-alpha.2

publish_to: "none"

environment:
  sdk: ^3.0.0
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  realm: ^2.0.0-beta.2
  characters: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
