name: IOS Build Combine

on:
  workflow_call:

jobs:
  build-ios-xcframework:
    name: Combine .xcframework
    timeout-minutes: 15
    runs-on: macos-latest

    steps:
      - name: Fetch device build
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
        with:
          name: librealm-ios-device
          path: binary/ios
      - name: Fetch simulator build
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
        with:
          name: librealm-ios-simulator
          path: binary/ios
      - name: Fetch catalyst build
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
        with:
          name: librealm-ios-catalyst
          path: binary/ios

      - name: Build .xcframework
        run: |
          xcodebuild -create-xcframework \
            -framework ./binary/ios/Release-iphoneos/realm_dart.framework \
            -framework ./binary/ios/Release-iphonesimulator/realm_dart.framework \
            -framework ./binary/ios/Release-maccatalyst/realm_dart.framework \
            -output ./binary/ios/realm_dart.xcframework
          rm -rf ./binary/ios/Release-*

      - name: Store .xcframework artifact
        uses: actions/upload-artifact@v4
        with:
          name: librealm-ios
          path: binary/ios
          retention-days: 1

      - name: Delete individual framework artifacts
        uses: geekyeggo/delete-artifact@54ab544f12cdb7b71613a16a2b5a37a9ade990af
        with:
          name: |
            librealm-ios-device
            librealm-ios-simulator
            librealm-ios-catalyst
