name: Android Build Combine

on:
  workflow_call:
   inputs:
      os:
        required: true
        type: string

jobs:
  build-android-combined:
    name: Combine Android binaries
    runs-on:  ${{ inputs.os }}-latest

    steps:
      - name: Fetch x86 build
        uses: actions/download-artifact@v2
        with:
          name: librealm-android-x86
          path: binary/android
      - name: Fetch x86_64 build
        uses: actions/download-artifact@v2
        with:
          name: librealm-android-x86_64
          path: binary/android
      - name: Fetch armeabi-v7a build
        uses: actions/download-artifact@v2
        with:
          name: librealm-android-armeabi-v7a
          path: binary/android
      - name: Fetch arm64-v8a build
        uses: actions/download-artifact@v2
        with:
          name: librealm-android-arm64-v8a
          path: binary/android

      - name: Store combined artifact
        uses: actions/upload-artifact@v2
        with:
          name: librealm-android
          path: binary/android
          retention-days: 1

      - name: Delete individual build artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            librealm-android-x86
            librealm-android-x86_64
            librealm-android-armeabi-v7a
            librealm-android-arm64-v8a