name: Build native

on:
  workflow_call:
    inputs:
      runner:
        description: Platforms to execute on.
        required: true
        type: string
      binary:
        description: Binary to build.
        required: true
        type: string
      build:
        description: Build for devices, in format of a string JSON array
        required: true
        type: string

jobs:
  build-native:
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        working-directory: packages/realm_dart
    name: Build native
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
         build: ${{ fromJSON(inputs.build) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Check cache
        id: check-cache
        uses: actions/cache@v4
        with:
          path: ./packages/realm_dart/binary/**
          key: binaries-${{ matrix.build }}-${{ inputs.runner }}-${{hashFiles('./packages/realm_dart/src/**')}}-debug

      - name: Setup Ninja
        if: steps.check-cache.outputs.cache-hit != 'true' && (startsWith(matrix.build, 'android') || startsWith(matrix.build, 'linux'))
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build

      - name: Setup Android NDK
        if: startsWith(matrix.build, 'android')
        run: echo "ANDROID_NDK=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV

      - name: Downgrade XCode for MacOS
        if: matrix.build == 'macos'
        run: sudo xcodes select 14.3.1

      - name: Build
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: |
          cmake --preset ${{ startsWith(matrix.build, 'ios-') && 'ios' || matrix.build }}
          cmake --build --preset ${{ matrix.build }} --config Debug

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: librealm-${{ matrix.build }}
          path: packages/realm_dart/binary/${{ inputs.binary }}/**
          retention-days: 1
          if-no-files-found: error
