name: Build native

on:
  workflow_call:
    inputs:
      runner:
        description: Platforms to execute on.
        required: true
        type: string
      binary:
        description: Binary to build.
        required: true
        type: string
      build:
        description: Build for devices, in format of a string JSON array
        required: true
        type: string

jobs:
  build-native:
    runs-on: ${{ inputs.runner }}-latest
    name: Build native
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
         build: ${{ fromJSON(inputs.build) }}
    steps:
      - name: Checkout
        uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445
        with:
          submodules: 'recursive'

      - name: Check cache
        id: check-cache
        if: ${{ !contains(github.head_ref, 'release/') }}
        uses: actions/cache@v3
        with:
          path: ./binary/**
          key: binaries-${{ matrix.build }}-${{hashFiles('./src/**')}}

      - name: Setup Ninja
        if: contains(github.head_ref, 'release/') || steps.check-cache.outputs.cache-hit != 'true'
        uses: seanmiddleditch/gha-setup-ninja@1815f2d05c2cd60c2d900f89843139b8dde09f4c

      - name: Get vcpkg submodule commit sha
        id: vcpkg_cache_key
        if: contains(github.head_ref, 'release/') || steps.check-cache.outputs.cache-hit != 'true'
        working-directory: src/realm-core/tools/vcpkg/ports
        shell: bash
        run: echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Setup Vcpkg
        if: contains(github.head_ref, 'release/') || steps.check-cache.outputs.cache-hit != 'true'
        continue-on-error: true
        uses: friendlyanon/setup-vcpkg@v1
        with:
          path: src/realm-core/tools/vcpkg/ports
          cache-key: vcpkg-${{ matrix.build }}-${{ steps.vcpkg_cache_key.outputs.commit }}-${{ hashFiles('./src/realm-core/tools/vcpkg/vcpkg.json') }}
          cache-restore-keys: vcpkg-${{ matrix.build }}-${{ steps.vcpkg_cache_key.outputs.commit }}-

      - name: Refetch Vcpkg
        run: git fetch --unshallow
        working-directory: ./src/realm-core/tools/vcpkg/ports

      - name: Setup Android NDK
        if: startsWith(matrix.build, 'android-')
        run: echo "ANDROID_NDK=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV

      - name: Build
        if: ${{ contains(github.head_ref, 'release/') || steps.check-cache.outputs.cache-hit != 'true' }}
        run: |
          cmake --preset ${{ startsWith(matrix.build, 'ios-') && 'ios' || matrix.build }}
          cmake --build --preset ${{ matrix.build }} --config Release

      - name: Store artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: librealm-${{ matrix.build }}
          path: binary/${{ inputs.binary }}/**
          retention-days: 1
